### ISSUE TITLE
Hardcoded jamf URL 

### ISSUE THREAD

**Issue by grahamr** [chrisgzim/jamfscripts#3]
You have your sample URL hardcoded - should refer to the variable i think? 

https://github.com/chrisgzim/jamfscripts/blob/f3c659d9ffd9728b4713bfe24303d562a48ce5a7/Recovery%20Lock#L132

**Comment by chrisgzim** [comment]
You are absolutely correct @grahamr! Thank you for the catch I am fixing it now
