### ISSUE TITLE
Recovery Lock script not sending to all devices

### ISSUE THREAD

**Issue by joshnovotny** [chrisgzim/jamfscripts#4]
Hello,

I am the Jamf customer who requested a way to mass deploy recovery lock last week. I am trying to run this script, but it doesn't seem to run on all the computers in the smart group. The first smart group I tried had 1600+ Macbooks in it, and it ran on 56 computers. I tried again with a more narrow smart group of ~500 and it ran on 76 computers.

I am counting by the number of times the output came back as:

```
} ][ {
  "id" : "$mgmtid",
  "href" : "https://casper.isd720.com/shakopee/api/v1/mdm/commands?uuids=$mgmtid"
```

An error also does occur in terminal right before the smart group selector pops up:

```
Traceback (most recent call last):
  File "/Users/Shared/ManagementID.py", line 5, in <module>
    print("" + data["results"][x]['serialNumber'] + ("," + data["results"][x]['managementId']))
          ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
0
```

Thanks!

**Comment by chrisgzim** [comment]
Hey @joshnovotny! Thank you for the feedback, going to look into how information is being parsed out of the json document. Wondering if it is scraping blank values. Not a python expert, but need to add some logic for blank values!

**Comment by chrisgzim** [comment]
Hey @joshnovotny just posted a new script that should fix the second error. Will be working on a fix for the issue on not all of the computers getting the command / work on logging logic.

**Comment by chrisgzim** [comment]
Hey @joshnovotny! Thank you again for all of your help in making sure this script is running properly. I am going to close this issue out now. V5 is on its way with some welcomed improvements!
